// Yerleşik egzersiz kataloğu.
import {all7} from './sabitler.js';
import {yeniEgzersizler} from './yeni-egzersizler.js';

/* ══════════════ KATALOG ══════════════ */
export function T(a){return a.map(x=>({sets:x[0],v:x[1]}));}
export function E(id,name,o){return Object.assign({id,name,unit:'tekrar',grp:'Seans',pattern:'',muscles:{},systems:{},days:[],targets:[],rpe:5,impact:false,halfRec:false,custom:false,step:0,note:'',tempo:'',recovery:'',fills:'',block:null,prereqId:null,prereqValue:0,prereqText:''},o);}
export const kCatalog=[
  E('push','Şınav',{pattern:'Yatay itme',grp:'Baz blok',muscles:{gogus:1,triseps:1,omuz:.5,core:.5},systems:{sinir:1,kasItme:.5},days:all7,targets:T([[6,5],[6,6],[6,7],[6,4]]),rpe:4,halfRec:true,step:2,note:'Günün içine yay. Konsantrik faz hızlı.'}),
  E('squat','Squat (3 sn iniş, 1 sn altta)',{pattern:'Diz baskın',grp:'Baz blok',muscles:{kuadriseps:1,gluteus:1,kalcaYan:.5},systems:{sinir:1,kasBacak:.5,tendonDiz:.5},days:all7,targets:T([[6,4],[6,5],[6,6],[6,3]]),rpe:4,halfRec:true,step:1,note:'Yavaş iniş, hızlı çıkış.'}),
  E('wallsit','Duvar oturuşu',{pattern:'Diz baskın (izometrik)',unit:'sn',grp:'Baz blok',muscles:{kuadriseps:1,gluteus:.5},systems:{tendonDiz:1,kasBacak:.5},days:all7,targets:T([[2,35],[2,40],[2,45],[2,30]]),rpe:5,halfRec:true,step:5}),
  E('wallpush','Duvar itme (hafif, 140°)',{pattern:'Yatay itme (izometrik)',unit:'sn',grp:'Baz blok',muscles:{gogus:1,triseps:1,omuz:.5,baldir:.5},systems:{tendonItme:1,sinir:.5},days:all7,targets:T([[2,40],[2,40],[2,40],[2,40]]),rpe:4,halfRec:true,note:'20 sn sol bacak geride, 20 sn sağ bacak geride.'}),
  E('chin','Chin-up (avuç içi sana)',{pattern:'Dikey çekme',grp:'Çekme',muscles:{lat:1,biseps:1,onkol:.5},systems:{sinir:1,kasCekme:1,tendonKol:.5},days:[1,4,6],targets:T([[3,1],[3,1],[3,1],[2,1]]),rpe:8,note:'Setler arası en az 1 saat.'}),
  E('pullNeg','Pull-up negatifi',{pattern:'Dikey çekme',grp:'Çekme',muscles:{lat:1,ustSirt:.5,biseps:.5,onkol:.5},systems:{sinir:.5,kasCekme:1,tendonKol:1},days:[2,5,7],targets:T([[3,1],[3,1],[3,1],[2,1]]),rpe:7,note:'Yukarı zıpla veya sandalyeden çık, 4-5 sn kontrollü in.'}),
  E('hang','Aktif asılma',{pattern:'Dikey çekme (izometrik)',unit:'sn',grp:'Çekme',muscles:{onkol:1,lat:.5,ustSirt:.5},systems:{tendonKol:1,mobilite:.5},days:[3],targets:T([[3,15],[3,15],[3,20],[3,15]]),rpe:4}),
  E('row1','Tek kol kürek (çanta)',{pattern:'Yatay çekme',muscles:{lat:1,ustSirt:1,biseps:.5,onkol:.5},systems:{kasCekme:1,sinir:.5},days:[1],targets:T([[3,8],[3,9],[3,10],[2,8]]),rpe:7,note:'Her kol için ayrı set. 3 sn iniş.'}),
  E('rdl1','Tek bacak RDL',{pattern:'Kalça baskın',muscles:{hamstring:1,gluteus:1,core:.5},systems:{kasBacak:1,sinir:.5,tendonKalca:.5},days:[1],targets:T([[3,6],[3,7],[3,8],[2,6]]),rpe:6,note:'Her bacak için ayrı set. 3 sn iniş.'}),
  E('bridge1','Tek bacak glüte köprüsü',{pattern:'Kalça baskın',muscles:{gluteus:1,hamstring:.5,core:.5},systems:{kasBacak:1,sinir:.5},days:[1],targets:T([[3,8],[3,9],[3,10],[2,8]]),rpe:6,note:'Üstte 2 sn bekle. Her bacak ayrı set.'}),
  E('deadbug','Dead bug',{pattern:'Core · bastırma',muscles:{core:1,coreRot:.5},systems:{sinir:1,kasGovde:.5},days:[1],targets:T([[3,6],[3,7],[3,8],[2,6]]),rpe:5}),
  E('sideplank','Yan plank',{pattern:'Core · rotasyon',unit:'sn',muscles:{coreRot:1,kalcaYan:.5,omuz:.5},systems:{tendonItme:.5,kasGovde:.5,sinir:.5},days:[1],targets:T([[2,20],[2,25],[2,30],[2,20]]),rpe:5,note:'Her yan ayrı set.'}),
  E('wallhard','Duvar itme (yüksek efor)',{pattern:'Yatay itme (izometrik)',unit:'sn',muscles:{gogus:1,triseps:1,omuz:1},systems:{tendonItme:1,sinir:.5},days:[1,4],targets:T([[4,10],[4,10],[4,10],[2,10]]),rpe:8,note:'Pzt: 100° ve 130° (2 set her açı). Per: 130° ve 160°.'}),
  E('bulgar','Bulgar split squat',{pattern:'Diz baskın (tek bacak)',muscles:{kuadriseps:1,gluteus:1,kalcaYan:.5},systems:{kasBacak:1,tendonDiz:.5,sinir:.5,kemik:.5},days:[4],targets:T([[0,0],[0,0],[3,5],[2,5]]),rpe:6,note:"Hafta 3'ten itibaren. Her bacak ayrı set."}),
  E('cossack','Cossack squat',{pattern:'Diz baskın (yan düzlem)',muscles:{kalcaYan:1,kuadriseps:.5,gluteus:.5},systems:{mobilite:1,kasBacak:.5,tendonDiz:.5},days:[4],targets:T([[0,0],[0,0],[3,5],[2,5]]),rpe:5,note:"Hafta 3'ten itibaren. Her yan ayrı set."}),
  E('hip9090','90/90 rotasyon',{pattern:'Mobilite',muscles:{kalcaYan:1,gluteus:.5},systems:{mobilite:1,sinir:.5},days:[4],targets:T([[0,0],[0,0],[2,5],[2,5]]),rpe:4,note:"Hafta 3'ten itibaren."}),
  E('bike','Bisiklet (koşu günü, 25 + 40 dk)',{pattern:'Kardiyo · düşük darbe',unit:'dk',muscles:{kuadriseps:.5,gluteus:.5,baldir:.5},systems:{aerobik:.5},days:[2],targets:T([[1,65],[1,65],[1,65],[1,65]]),rpe:3}),
  E('run','Koşu',{pattern:'Kardiyo · darbe',unit:'dk',muscles:{baldir:1,kuadriseps:.5,gluteus:.5,hamstring:.5},systems:{aerobik:1,kemik:1,tendonAsil:1},days:[2],targets:T([[1,15],[1,16],[1,17],[1,15]]),rpe:5,impact:true,note:'Konuşma temposu. Haftada en fazla +1 dk.'}),
  E('rope','İp atlama',{pattern:'Reaktif',unit:'dk',muscles:{baldir:1,kuadriseps:.5,omuz:.5,onkol:.5},systems:{reaktif:1,tendonAsil:1,kemik:.5,aerobik:.5},days:[5],targets:T([[1,5],[1,5],[1,5],[1,5]]),rpe:6,impact:true,note:'30 sn atla, 30 sn dinlen. Düşük sıçrama.'}),
  E('shadow','Gölge boks (3 dk raund)',{pattern:'Boks',unit:'dk',muscles:{omuz:1,coreRot:1,kuadriseps:.5,baldir:.5},systems:{anaerobik:1,sinir:1,aerobik:.5},days:[5],targets:T([[4,3],[4,3],[5,3],[3,3]]),rpe:7,note:'Her set bir raund, arada 1 dk dinlenme.'}),
  E('zone2','Uzun Zone 2 bisiklet',{pattern:'Kardiyo · düşük darbe',unit:'dk',muscles:{kuadriseps:.5,gluteus:.5,baldir:.5},systems:{aerobik:1},days:[6],targets:T([[1,60],[1,70],[1,80],[1,60]]),rpe:4,note:'Konuşma testi belirleyici.'}),
  E('yoga','Yoga / tam vücut esneme',{pattern:'Mobilite',unit:'dk',muscles:{hamstring:.5,kalcaYan:.5,omuz:.5,lat:.5},systems:{mobilite:1},days:[3,7],targets:T([[1,15],[1,15],[1,15],[1,15]]),rpe:2}),
  E('nordic','Kademeli Nordic curl',{pattern:'Kalça baskın',muscles:{hamstring:1,gluteus:.5},systems:{kasBacak:1,tendonKalca:1,sinir:.5},days:[4],targets:T([[3,3],[3,4],[3,5],[2,3]]),rpe:7,block:'Blok 2',prereqId:'rdl1',prereqValue:8,prereqText:'Tek bacak RDL 3×8, RPE 6 altında',fills:'Hamstring eksantrik kuvveti ve yaralanma direnci',note:'Ayak bileklerini sabitle, çok yavaş in, ellerle yumuşak karşıla.'}),
  E('pogo','Pogo hop (düşük genlik)',{pattern:'Reaktif',muscles:{baldir:1,kuadriseps:.5},systems:{reaktif:1,tendonAsil:1,kemik:.5},days:[5],targets:T([[3,10],[3,12],[3,15],[2,10]]),rpe:6,impact:true,block:'Blok 2',prereqId:'rope',prereqValue:5,prereqText:'İp atlamayı 5 dk sorunsuz bitir, Aşil sabah sertliği olmasın',fills:'Ayak bileği sertliği, reaktif güç',note:'Kısa yer teması, yumuşak zemin. Derinlik atlaması yok.'}),
  E('sprint','Bisiklet sprint aralığı',{pattern:'Kardiyo · düşük darbe',unit:'sn',muscles:{kuadriseps:1,gluteus:.5,baldir:.5},systems:{anaerobik:1,sinir:.5,aerobik:.5},days:[6],targets:T([[6,20],[8,20],[8,20],[4,20]]),rpe:9,block:'Blok 2',prereqId:'zone2',prereqValue:70,prereqText:'Zone 2 seansını 70 dk konuşma temposunda bitir',fills:'Anaerobik kapasite, düşük darbeli hız uyaranı',note:'20 sn tam gaz, 100 sn rahat. İki haftada bir Zone 2 yerine.'}),
  E('archer','Arşer şınav',{pattern:'Yatay itme',muscles:{gogus:1,triseps:1,omuz:.5,core:.5},systems:{sinir:1,kasItme:1,tendonItme:.5},days:[1,4],targets:T([[3,3],[3,4],[3,5],[2,3]]),rpe:7,block:'Blok 2',prereqId:'push',prereqValue:7,prereqText:'Şınav 6×7, RPE 6 altında',fills:'Yatay itme yoğunluğu, tek kol kuvveti',note:'Her yan ayrı set.'}),
  E('clap','Patlayıcı şınav (eller yerden kalkar)',{pattern:'Yatay itme',muscles:{gogus:1,triseps:1,omuz:.5},systems:{reaktif:1,sinir:1,tendonItme:.5},days:[1],targets:T([[4,3],[4,3],[4,4],[2,3]]),rpe:8,block:'Blok 2',prereqId:'push',prereqValue:10,prereqText:'Şınav set başına 10 tekrarı rahat yap',fills:'Üst vücut reaktif gücü (yumruk hızına transfer)',note:'Tam dinlenmeyle, yorgunken yapma.'}),
  E('pallof','Pallof press (bant)',{pattern:'Core · rotasyon',muscles:{coreRot:1,core:.5},systems:{sinir:1,kasGovde:.5},days:[4],targets:T([[3,8],[3,8],[3,10],[2,8]]),rpe:5,block:'Bant gerekli',prereqText:'Direnç bandı al',fills:'Anti-rotasyon core',note:'Her yan ayrı set.'}),
  E('carry','Çanta taşıma (loaded carry)',{pattern:'Taşıma',unit:'sn',muscles:{onkol:1,core:1,ustSirt:.5,baldir:.5},systems:{kasCekme:.5,tendonKol:.5,kemik:.5,sinir:.5},days:[1],targets:T([[3,30],[3,40],[3,45],[2,30]]),rpe:6,block:'Blok 2',prereqText:'Kriter yok, hazır hissettiğinde ekle',fills:'Taşıma kalıbı, kavrama, gövde stabilitesi',note:'Bir elde ağır çanta. Dik dur, omuzlar kapalı.'}),
  E('pullup','Pull-up (tam tekrar)',{pattern:'Dikey çekme',grp:'Çekme',muscles:{lat:1,ustSirt:.5,biseps:.5,onkol:.5},systems:{sinir:1,kasCekme:1,tendonKol:.5},days:[2,5,7],targets:T([[3,1],[3,1],[3,1],[2,1]]),rpe:8,block:'Hedef',prereqId:'chin',prereqValue:2,prereqText:'Chin-up 2 tekrar ve negatif 5 sn kontrollü',fills:'Dikey çekme hedefi',note:'Negatifin yerine geçer, ekleyince negatifi kapat.'}),
].concat(yeniEgzersizler(E,T));
